server:
  # 端口
  port: 8080
  # 项目名
  #context-path: /shiro

  servlet:
    session:
      cookie:
        name: HL-SESSION

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1qaz2wsx
    driverClassName: com.mysql.jdbc.Driver